name: foxbit_hiring_test_template
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clean_architecture: ^6.0.1
  intl: ^0.19.0
  rxdart: ^0.27.7
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  lint: 2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Noyh R
      fonts:
        - asset: assets/fonts/noyh-r-regular.ttf
    - family: Noyh R Bold
      fonts:
        - asset: assets/fonts/noyh-r-bold.otf